
from . import hms_room
from . import bed
from . import hms_disease
from . import hr_department
from . import consumable_line
from . import hms_insurance
from . import hms_role
from . import res_partner
from . import hr_employee
from . import hms_case
from . import hms_medicalrecord
from . import hms_dashboards
from . import hms_appointment
from . import hms_prescription
from . import hms_prescription_line
from . import hms_lab_request
from . import hms_lab_request_line
from . import hms_lab_result
from . import product_template
from . import wizards
from . import hms_notes
from . import stock_location