{
    'name': 'hms',
    'version': '1.1',
    'summary': 'hospital management system',
    'description': '',
    'category': 'hospital',
    'author': 'script surgeons',
    "depends": [
    "base",
    "web",
    "auth_signup",
    "contacts",
    "calendar",
    "product",
    'account_payment',
    "stock",
    "account",
    "portal",
    "hr",
    "mail",
],
    'data': [
        'data/new_signup_email.xml',
        'data/company_setup.xml',
        'report/report_template.xml',
        'views/hms_actions.xml',
        'security/hms_groups.xml',
        'security/ir.model.access.csv',
        'security/hms_record_rules.xml',
        'data/mail_templates.xml',
        'data/sequence.xml',
        'views/hms_prescription_views.xml',
        'views/hms_lab_request_views.xml',
        'views/hms_lab_result_views.xml',
        'report/lab_result_template.xml',
        'report/case_summary_template.xml',
        'views/hr_department.xml',
        'views/hms_room_views.xml',
        'views/hms_disease_views.xml',
        'views/hms_insurance_views.xml',
        'views/portal/main.xml',
        'views/portal/medical_record_template.xml',
        'views/portal/appointments_template.xml',
        'views/portal/cases_template.xml',
        'views/portal/prescriptions_template.xml',
        'views/portal/appointment_request_template.xml',
        'views/portal/labs_template.xml',
        'views/res_partner_views.xml',
        'views/hms_appointment_views.xml',
        'views/hms_medical_record_views.xml',
        'views/hms_case_views.xml',
        'views/hms_dashboards.xml',
        'views/wizards/employee_password_wizard.xml',
        'views/hr_employee_views.xml',
        'data/hr_jobs.xml',
        'data/hms_role_data.xml',
        'data/cron_appointment.xml',
        'views/hms_bed_views.xml',
        'views/hms_patient_website.xml',
        'views/hms_consumable_line_views.xml',
        'views/product_views.xml',
        'views/wizards/md_wizard_view.xml',
        'views/wizards/grant_portal_wizard_view.xml',
        'views/web_templates.xml',
        'views/hms_notes_views.xml',
        'views/hide_menu.xml',
        'report/prescription_template.xml',
        'report/invoice_template.xml',
        'report/reports_last7.xml',
        'views/hms_case_print_summary_primary.xml',
        'report/admin_summary_30d.xml',
        'views/hms_menu.xml',
    ],
    'assets': {
        'web.assets_frontend': [
    'hms/static/src/scss/login.scss',

    ],
        'web.assets_backend': [
            'hms/static/src/js/statics_service.js',
            'hms/static/src/js/hms_dashboards.js',
            'hms/static/src/xml/hms_dashboards.xml',
            'hms/static/src/scss/login.scss',
            'hms/static/src/scss/patient-style.scss',
            'hms/static/src/img/icons8-pill-96.png',
            'hms/static/src/img/icons8-result-98.png',
            'hms/static/src/img/icons8-pill-100.png',
            "web/static/lib/Chart/Chart.js",
        ],
    },

    'application': True,
    'installable': True,
    'license': 'LGPL-3',

}
